version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - "8242:8080"
    environment:
      PORT: 8080
      SECRET: "9ernewf0w34jnf0324nfwdssdofhn3240f24fs"
      DB_DSN: "root:passw@mariadb/unbottled"
    volumes:
      - uploads_vol:/app/uploads
    networks:
      - net

  mariadb:
    image: mariadb
    restart: always
    ports:
      - "8243:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passw
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - net

volumes:
  uploads_vol:
  mariadb_vol:

networks:
  net: